### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by tagrimo** [mja00/alphaskins#2]
Would you consider porting the mod to fabric? I know it was originally a fabric mixin but no other mod exists that lets you use transparent pixels on skins and I NEED it.
Thank you!

**Comment by mja00** [comment]
In theory it's a lot easier to port between Fabric and Forge due to using the same mappings. I'll take a look into updating it and porting to Fabric.

**Comment by mja00** [comment]
@tagrimo Do you need a specific Fabric version or is 1.21.X fine?

**Comment by tagrimo** [comment]
I use 1.20.1, and I probably won't ever update past it. Thank you for the response!

**Comment by mja00** [comment]
Sweet, easy to move the mixin over then. Annoyingly there's 3 different changes to the mixins for 1.21.X lol

I'll look into porting it to fabric in the next few days.

**Comment by mja00** [comment]
@tagrimo shockingly easy. Can find it here https://modrinth.com/mod/alphaskins/version/xMfz9PSe or build it yourself :D

**Comment by tagrimo** [comment]
Thank you, you a real one
